# Site settings
title: Downer Startup
description: > # this means to ignore newlines until "baseurl:"
 The blog of a japanese entreprener who is at the same time a web engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tarky.github.io" # the base hostname & protocol for your site
github_username: tarky 

# Build settings
markdown: kramdown
